site_name: 2020_5AI_Team7

nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management Plan': 'Software Project Management Plan.md'
    - 'Project Model Canvas': 'Project Model Canvas.pdf'
    - 'Business Model Canvas': 'Business Model Canvas.pdf'
    - 'Release Plan': 'Release Plan.md'
    - 'System Requirements Specification': 'System Requirements Specification.md'
    - 'Test Plan': 'Test Plan.md'
    - 'Test Case Specification': 'Test Case Specification.md'
    - 'Project Success Criteria': 'Project Success Criteria.md'
    - 'User Guide': 'User Guide.md'
    - 'Architecture, Design and Coding standards': 'Architecture, Design and Coding standards.md'
    - 'Iteration Plan': 'Iteration Plan.md'
    - 'Memo of Understanding': 'Memo of Understanding.md'
    - 'Data Protection Agreement': 'Data Protection Agreement.md'
    
    - 'Project Charter': 'Project Charter.pdf'
    - 'Software Requirements Specification': 'Software Requirements Specification.pdf'
    - 'Software Project Management Plan': 'Software Project Management Plan.pdf'
    - 'Release Plan': 'Release Plan.pdf'
    - 'System Requirements Specification': 'System Requirements Specification.pdf'
    - 'Test Plan': 'Test Plan.pdf'
    - 'Test Case Specification': 'Test Case Specification.pdf'
    - 'Project Success Criteria': 'Project Success Criteria.pdf'
    - 'User Guide': 'User Guide.pdf'
    - 'Architecture, Design and Coding standards': 'Architecture, Design and Coding standards.pdf'
    - 'Iteration Plan': 'Iteration Plan.pdf'
    - 'Memo of Understanding': 'Memo of Understanding.pdf'
    - 'Data Protection Agreement': 'Data Protection Agreement.pdf'
   
    
theme:
    name: readthedocs

