site_name: 2020_5AI_Team7

nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management Plan': 'Software Project Management Plan.md'
   
    
theme:
    name: readthedocs

