site_name: 2020_5AI_Team7

nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management Plan': 'Software Project Management Plan.md'
    - 'Project Model Canvas': 'Project Model Canvas.pdf'
    - 'Business Model Canvas': 'Business Model Canvas.pdf'
    - 'Release Plan': 'Release Plan.md'
    - 'System Requirements Specification': 'System Requirements Specification.md'
    - 'Test Plan': 'Test Plan.md'
    - 'Test Case Specification': 'Test Case Specification.md'
    - 'Project Success Criteria': 'Project Success Criteria.md'
   
    
theme:
    name: readthedocs

